name: Setup Deploy Keys
description: Run `ssh-agent` and load SSH keys to access other private repositories

branding:
  icon: loader
  color: 'yellow'

inputs:
  deploy-key-info:
    description: 'An array of deploy key info objects that contain the org and repo the deploy key is intended for as well as the name of the envioronment variable that contains the value of the private key.'
    required: true
outputs:
  validation-error:
    description: 'A string with a short description of a validation error that occurred.  Generally used for testing but can be used programmatically to detect which types of validation errors the action is encountering.'
  key-filename:
    description: 'The name of the file where the key was written to disk.  Generally used for testing because the output would only reflect the last key that was processed.'
    
runs:
  using: 'node16'
  main: 'dist/index.js'
  post: 'dist/cleanup.js'
  post-if: 'always()'
